---
ansible_python_interpreter: "{{ ansible_playbook_python }}"

panos_provider:
  ip_address: "{{ ansible_host }}"
  username: "{{ lookup('env', 'PANOS_USERNAME') | default(panos_username, true) }}"
  password: "{{ lookup('env', 'PANOS_PASSWORD') | default(panos_password, true) }}"
