---
- name: Configure firewall
  hosts: all
  connection: local
  gather_facts: false
  
  tasks:

    - name: Configure FW interfaces
      paloaltonetworks.panos.panos_interface:
        provider: "{{ panos_provider }}"
        if_name: "{{ item.if_name }}"
        mode: "{{ item.mode }}"
        ip: "{{ item.ip }}"
        enable_dhcp: "{{ item.enable_dhcp }}"
        commit: false
        state: "{{ fw_config_state | default('present') }}"
      with_items: "{{ fw_interfaces }}"
      tags: network

    - name: Configure virtual router
      paloaltonetworks.panos.panos_virtual_router:
        provider: "{{ panos_provider }}"
        name: "default"
        interface: [ 'ethernet1/1', 'ethernet1/2', 'ethernet1/3' ]
        commit: false
        state: "{{ fw_config_state | default('present') }}"
      tags: network

    - name: Configure static route
      paloaltonetworks.panos.panos_static_route:
        provider: '{{ panos_provider }}'
        virtual_router: 'default'
        name: 'default'
        destination: '0.0.0.0/0'
        nexthop: '10.0.0.2'
        state: "{{ fw_config_state | default('present') }}"
      tags: network

    - name: Configure zones
      paloaltonetworks.panos.panos_zone:
        provider: "{{ panos_provider }}"
        zone: "{{ item.zone }}"
        mode: "{{ item.mode }}"
        interface: "{{ item.interfaces }}"
        state: "{{ fw_config_state | default('present') }}"
      with_items: "{{ fw_zones }}"
      tags: network

    - name: Create address objects
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ panos_provider }}'
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        commit: false
        state: "{{ fw_config_state | default('present') }}"
      with_items: '{{ fw_address_objects }}'
      tags: objects