---
fw_security_rules:
  - rule_name: "Allow ping"
    location: "top"
    source_zone: ["any"]
    source_ip: ["any"]
    source_user: ["any"]
    destination_zone: ["any"]
    destination_ip: ["any"]
    application: ["ping"]
    service: ["application-default"]
    category: ["any"]
    action: "allow"
    log_start: false
    log_end: true
    rule_type: "universal"
    negate_source: false
    negate_destination: false
    disabled: false
    state: present

  - rule_name: "Allow SSH inbound"
    location: "after"
    existing_rule: "Allow ping"
    source_zone: ["untrust"]
    source_ip: ["any"]
    source_user: ["any"]
    destination_zone: ["web", "db"]
    destination_ip: ["any"]
    application: ["ssh"]
    service: ["application-default"]
    category: ["any"]
    action: "allow"
    log_start: false
    log_end: true
    rule_type: "universal"
    negate_source: false
    negate_destination: false
    disabled: false
    state: present

  - rule_name: "Allow inbound web"
    location: "after"
    existing_rule: "Allow SSH inbound"
    source_zone: ["untrust"]
    source_ip: ["any"]
    source_user: ["any"]
    destination_zone: ["web"]
    destination_ip: ["any"]
    application: ["web-browsing", "ssl"]
    service: ["application-default"]
    category: ["any"]
    action: "allow"
    log_start: false
    log_end: true
    rule_type: "universal"
    negate_source: false
    negate_destination: false
    disabled: false
    state: present

  - rule_name: "Allow web to db"
    location: "after"
    existing_rule: "Allow inbound web"
    source_zone: ["web"]
    source_ip: ["web-server"]
    source_user: ["any"]
    destination_zone: ["db"]
    destination_ip: ["db-server"]
    application: ["mysql"]
    service: ["application-default"]
    category: ["any"]
    action: "allow"
    log_start: false
    log_end: true
    rule_type: "universal"
    negate_source: false
    negate_destination: false
    disabled: false
    state: present

  - rule_name: "Allow all outbound"
    location: "after"
    existing_rule: "Allow web to db"
    source_zone: ["web", "db"]
    source_ip: ["any"]
    source_user: ["any"]
    destination_zone: ["untrust"]
    destination_ip: ["any"]
    application: ["any"]
    service: ["application-default"]
    category: ["any"]
    action: "allow"
    log_start: false
    log_end: true
    rule_type: "universal"
    negate_source: false
    negate_destination: false
    disabled: false
    state: present
