---
- name: Configure firewall
  hosts: pa_fw
  connection: local

  tasks:
    - name: Configure FW interfaces
      paloaltonetworks.panos.panos_interface:
        provider: "{{ panos_provider }}"
        if_name: "{{ item.if_name }}"
        mode: "{{ item.mode }}"
        ip: "{{ item.ip }}"
        enable_dhcp: "{{ item.enable_dhcp }}"
        commit: false
        state: "{{ fw_config_state | default('present') }}"
      loop: "{{ fw_interfaces }}"
      tags: network

    - name: Configure virtual router
      paloaltonetworks.panos.panos_virtual_router:
        provider: "{{ panos_provider }}"
        name: "{{ fw_virtual_router.name }}"
        interface: "{{ fw_virtual_router.interfaces }}"
        commit: false
        state: "{{ fw_config_state | default('present') }}"
      tags: network

    - name: Configure static routes
      paloaltonetworks.panos.panos_static_route:
        provider: "{{ panos_provider }}"
        virtual_router: "{{ item.virtual_router }}"
        name: "{{ item.name }}"
        destination: "{{ item.destination }}"
        nexthop: "{{ item.nexthop }}"
        state: "{{ fw_config_state | default('present') }}"
      loop: "{{ fw_static_routes }}"
      tags: network

    - name: Configure zones
      paloaltonetworks.panos.panos_zone:
        provider: "{{ panos_provider }}"
        zone: "{{ item.zone }}"
        mode: "{{ item.mode }}"
        interface: "{{ item.interfaces }}"
        state: "{{ fw_config_state | default('present') }}"
      loop: "{{ fw_zones }}"
      tags: zones

    - name: Configure address objects
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ panos_provider }}"
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        commit: false
        state: "{{ fw_config_state | default('present') }}"
      loop: "{{ fw_address_objects }}"
      tags: objects
