---
- name: Show firewall info
  hosts: pa_fw
  connection: local

  tasks:
    - name: Debug credential env vars
      ansible.builtin.debug:
        msg:
          - "ENV username: {{ lookup('env', 'PANOS_USERNAME') }}"
          - "ENV password length: {{ lookup('env', 'PANOS_PASSWORD') }}"
      tags: always

    - name: Gather FW facts
      paloaltonetworks.panos.panos_facts:
        provider: "{{ panos_provider }}"
        gather_subset: ["all"]
      tags: facts

    - name: Print FW facts
      ansible.builtin.debug:
        msg:
          - "Hostname: {{ ansible_net_hostname }}"
          - "Version: {{ ansible_net_version }}"
          - "Uptime: {{ ansible_net_uptime }}"
      tags: facts

    - name: Print whole configuration
      ansible.builtin.debug:
        msg: "{{ ansible_net_config | ansible.utils.from_xml }}"
      tags: facts

    - name: Get admin accounts info
      paloaltonetworks.panos.panos_op:
        provider: "{{ panos_provider }}"
        cmd: "show admins all"
      register: admins_info
      tags: admins

    - name: Print admin accounts info
      ansible.builtin.debug:
        msg: "{{ admins_info.stdout }}"
      tags: admins
